[package]
name = "tarnished-doom"
version = "0.1.0"
authors = ["Stephan van Ellewee <stephan.vanellewee@takealot.com>"]
build = "build.rs"


[build-dependencies]
cc = { version = "1.0.14", features = ["parallel"] }
